# Generated by Django 3.2.5 on 2021-07-16 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('INPUT', 'Произвольный текст'), ('SELECT', 'Выпадающий список'), ('RADIO', 'Один выбор'), ('CHECKED', 'Множественный выбор')], default='RADIO', max_length=255)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('date_of_published', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Показывать снова')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='csat.applicationquestion', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
    ]
