# Generated by Django 3.2.5 on 2021-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0002_auto_20210716_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='answer',
            field=models.JSONField(editable=False, max_length=255, null=True, verbose_name='Ответ'),
        ),
    ]
