# Generated by Django 3.2.5 on 2021-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0003_applicationquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Проходить снова'),
        ),
    ]
