# Generated by Django 3.2.5 on 2021-07-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0005_rename_questions_applicationquestion_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('anwer_option', models.CharField(blank=True, max_length=255, null=True, verbose_name='Варианты ответов')),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='csat.applicationquestion', verbose_name='Вопросы')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
