# Generated by Django 3.2.5 on 2021-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0007_rename_questionansweroptions_answeroptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroptions',
            options={'verbose_name': 'Варианты ответов', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.RemoveField(
            model_name='answeroptions',
            name='questions',
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='answer_options', to='csat.ApplicationQuestion', verbose_name='Вопросы'),
        ),
    ]
