# Generated by Django 3.2.5 on 2021-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0010_rename_anwer_option_answeroptions_answer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='time_to_answer',
            field=models.CharField(max_length=20, null=True, verbose_name='Время потраченное на ответ'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='answer',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Ответ'),
        ),
    ]
