# Generated by Django 3.2.5 on 2021-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0011_auto_20210718_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='date_answer',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Дата и время предоставления ответа'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='time_to_answer',
            field=models.CharField(editable=False, max_length=20, null=True, verbose_name='Время потраченное на ответ'),
        ),
    ]
