# Generated by Django 3.2.5 on 2021-07-23 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csat', '0012_auto_20210718_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
