# Generated by Django 3.2.5 on 2021-07-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csat', '0015_auto_20210723_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='question',
        ),
        migrations.AddField(
            model_name='userquestions',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forms', to='csat.applicationform', verbose_name='Опросник'),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
