# Generated by Django 3.2.5 on 2021-07-23 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csat', '0016_auto_20210723_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestions',
            new_name='UserApplicationForm',
        ),
    ]
