# Generated by Django 3.2.5 on 2021-07-17 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210717_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='changed_at',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Создан'),
        ),
    ]
