# Generated by Django 3.2.5 on 2021-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='additional_data',
            field=models.JSONField(editable=False, null=True, verbose_name='Доп. информация'),
        ),
    ]
