# Generated by Django 3.2.5 on 2021-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='filter_types',
            field=models.JSONField(null=True),
        ),
    ]
